### ISSUE TITLE
Is there known bugs ?

### ISSUE THREAD

**Issue by ghost** [felipenoris/actix-reverse-proxy#1]
I,

Thank you for this piece of software, it's exactly what I'm looking for.

Before using it, is there any bug that I should be aware ?

Like webaockets / long lived connections support ? Large payload ?

Concurrency limits ?

Kind regards

**Comment by felipenoris** [comment]
Hi! This package works for simple stuff. But I can't get it to work when I chain two reverse proxies, possibly due to a bug in the way *actix-web* implements the HTTP protocol.

The thread discussing this problem is this one: https://github.com/DoumanAsh/actix-reverse-proxy/issues/2

Since then, I stopped working in this code, and I'm working on a reverse proxy based on hyper. Please, check the *fn/dev* branch of [this repo](https://github.com/felipenoris/hyper-reverse-proxy/tree/fn/dev). The reverse proxy is rock solid with hyper, but does not support websockets, AFAIK.

**Comment by ghost** [comment]
Ok, thank you !
